version: '3'
services:
  jenkins-master:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    expose:
      - "50000"
      - "50001"
    volumes:
      - jenkins-data:/var/jenkins
  slave-java-11:
    build: slave-java-11
    environment:
      - JENKINS_MASTER_SERVER=jenkins-master
      - JENKINS_MASTER_PORT=8080
      - JENKINS_MASTER_JNLP_PORT=50000
      - JENKINS_TOKEN=ebce2562070dae899fd59ecf5d5bac7f7095a4ef5f5212667cae7d3d2e8f7206
      - SLAVE_NAME=slave-java-11
    depends_on:
      - jenkins-master
  slave-java-8:
    build: slave-java-8
    environment:
      - JENKINS_MASTER_SERVER=jenkins-master
      - JENKINS_MASTER_PORT=8080
      - JENKINS_MASTER_JNLP_PORT=50000
      - JENKINS_TOKEN=8a7b4385b0f5358b819f4fb261c7557a1f3b672eaf65d10c31c6f2dd9f44be39
      - SLAVE_NAME=slave-java-8
    depends_on:
      - jenkins-master
volumes:
  jenkins-data:
