version: '3'
services:
  jenkins-master:
    build: .
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"
      - "50001:50001"
      - "50002:50002"
    expose:
      - "50000"
      - "50001"
      - "50002"
    volumes:
      - jenkins-data:/var/jenkins
  slave-java-11:
    build: slave-java-11
    environment:
      - JENKINS_MASTER_SERVER=3.122.97.139
      - JENKINS_MASTER_PORT=8080
      - JENKINS_MASTER_JNLP_PORT=50000
      - JENKINS_TOKEN=0c8e3e8d8de756c5a049e9c13635b5cdfe1e61725de31cfe15f1a7cf48268fa2
      - SLAVE_NAME=slave-java-11
    depends_on:
      - jenkins-master
  slave-java-8:
    build: slave-java-8
    environment:
      - JENKINS_MASTER_SERVER=3.122.97.139
      - JENKINS_MASTER_PORT=8080
      - JENKINS_MASTER_JNLP_PORT=50001
      - JENKINS_TOKEN=5603473e822fc48418d7e2d3a153bd651a5cc30e6a15e7c362da20b20d4ba6b7
      - SLAVE_NAME=slave-java-8
    depends_on:
      - jenkins-master
  slave-android:
    build: slave-android
    environment:
      - JENKINS_MASTER_SERVER=3.122.97.139
      - JENKINS_MASTER_PORT=8080
      - JENKINS_MASTER_JNLP_PORT=50002
      - JENKINS_TOKEN=b0ba4d14636d31570318692b2e214cfbdb6e221b5351f263bff75e2c806dd730
      - SLAVE_NAME=slave-android
    depends_on:
      - jenkins-master
volumes:
  jenkins-data:
